# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-06-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_lecture_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
